version: '3'

services:
  app:
    image: lbadlani/js-engine-tee:app-v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8888
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    environment:
      - GRANT_SUDO=yes
      - NODE_ENV=production
      - CRON_SECONDS=15
    user: root